[build]
builder = "nixpacks"

[deploy]
startCommand = "cd apps/OpenSign && npx serve -s dist -l 8080"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.environment]
NODE_ENV = "production"
